name: Lee Chazen
favicon: null
layout_spectrum: 0.86811
typography_spectrum: 0.7515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#323232'
    - '#646464'
    - '#8c8c8c'
    - '#a6a8ab'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
