name: Lee Chazen
favicon: null
layout_spectrum: 0.05534126190468669
typography_spectrum: 0.1810428462922573
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#112830'
    - '#9ec8f2'
    - '#fffeff'
    - '#3a5da1'
    - '#766146'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
