name: Lee Chazen
favicon: null
layout_spectrum: 0.05534126190468669
typography_spectrum: 0.1810428462922573
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9816283257678151
  lightness: 0.06771973171271384
  saturation: 0.6939629919361323
  rhythmicContrast: 0.6488706965465099
purpose: []
