analytics: {}
color:
  brandColors:
    - '#fafafa'
    - '#323232'
    - '#646464'
    - '#8c8c8c'
    - '#a6a8ab'
  brandStrength: 0.5
  lightness: 0.6875
  rhythmicContrast: 0.75
  saturation: 0.5
cta: {}
layout_spectrum: 0.600225
name: Lee Chazen
opengraph: {}
purpose: []
typography_spectrum: 0.7515
